# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200817_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='techs',
            field=models.ManyToManyField(blank=True, related_name='techs', to='projects.Techs'),
        ),
    ]
