# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Kura',
        ),
    ]
