# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200817_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kura',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='kura',
            old_name='Design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='kura',
            old_name='Usability',
            new_name='usability',
        ),
    ]
